%% Homework 5, Problem 4 (Chapter 8, Problem 3)
%      MagicEightBall.m
%      Write a program that simulates a Magic8 Ball answer to a question
%      Author: Chris Kreienkamp
clear
clc
rng('shuffle')  % Good programming practice when using rand or randi

%% SET PARAMETERS
% Ask user for a question
ask = input('Ask me a yes/no question and I will predict the answer! ','s');

% Cell array with 10 entries
answer = {'It is certain',...
    'Yes--definitely',...
    'Signs point to yes',...
    'Without a doubt',...
    'Don''t count on it',...
    'Very doubtful',...
    'My sources say no',...
    'Outlook not so good',...
    'Better not tell you now',...
    'Cannot predict now'...
    'Well duhhh...'};

%% RANDOMIZE AND DISPLAY TO USER
sizeAnswer = length(answer);    % Determine the size of cell array
randAnswer = randi(sizeAnswer); % Pick a random answer
disp(answer(randAnswer))        % Display answer