function MagicEightBallF(handles)
%      Write a program that simulates a Magic8 Ball answer to a question
%      Author: Chris Kreienkamp
rng('shuffle')  % Good programming practice when using rand or randi

% Cell array with 10 entries
answer = {'It is certain',...
    'Yes--definitely',...
    'Signs point to yes',...
    'Without a doubt',...
    'Don''t count on it',...
    'Very doubtful',...
    'My sources say no',...
    'Outlook not so good',...
    'Better not tell you now',...
    'Cannot predict now'...
    'Well duhhh...'};

%% RANDOMIZE AND DISPLAY TO USER
sizeAnswer = length(answer);    % Determine the size of cell array
handles.replyText.String = answer(randi(sizeAnswer)); % Pick a random answer
