%% Homework 5, Problem 1
% randCount.m
% Randomly generate a number between 0 and 1
% Continue to randomly generate a number between 0 and 1 until the value is
% between 0.6 and 0.7 and track the number of values generated until then
% Find the average number of values that need to be generated by running
% this trial at least 1000 times
% Display the value
% Author: Chris Kreienkamp
clear
clc
rng('shuffle')

%% SET PARAMETERS
% Maximum value of range and minimum value of range
maxRange = 0.7;
minRange = 0.6;

numValues = 0;      % Initializes the number of values generated
numTrial = 1000;    % Decides the number of repetitions of the trial
          

%% RANDOMLY GENERATE NUMBER AND RUN 1000 TIMES
% Create for loop which runs the program 1000 times
% Create while loop that actually generates the values
for iCounter = 1:numTrial
    rNum = 2;           % Initializes the value
    while rNum < minRange || rNum > maxRange
        rNum = rand(1);
        numValues = numValues + 1;
    end
end

%% CALCULATE AVERAGE NUMBER OF GENERATED VALUES NEEDED
average = numValues / numTrial;
disp(['The average number of random values generated is ',num2str(average)])
